const Discord = require("discord.js");
module.exports={
    name: 'topic',
   category: "topic",
    run: async(bot, message, args) =>{
            let responses = [
                "What was the last funny video you saw?",
                "What do you do to get rid of stress?",
                "What is something you are obsessed with?",
                "What three words best describe you?",
                "What would be your perfect weekend?",
                "What’s your favorite number? Why?",
                "What are you going to do this weekend?",
                "What’s the most useful thing you own?",
                "What’s your favorite way to waste time?",
                "What do you think of tattoos? Do you have any?",
                "Do you have any pets? What are their names?",
                "Where did you go last weekend? / What did you do last weekend?",
                "What is something popular now that annoys you?",
                "What did you do on your last vacation?",
                "When was the last time you worked incredibly hard?",
                "Are you very active, or do you prefer to just relax in your free time?",
                "What do you do when you hang out with your friends?",
                "Who is your oldest friend? Where did you meet them?",
                "What’s the best / worst thing about your work/school?",
                "If you had intro music, what song would it be? Why?",
                "What were you really into when you were a kid?",
                "If you could have any animal as a pet, what animal would you choose?",
                "Have you ever saved an animal’s life? How about a person’s life?",
                "If you opened a business, what kind of business would it be?",
                "Who is your favorite entertainer (comedian, musician, actor, etc.)?",
                "Are you a very organized person?",
                "Have you ever given a presentation in front of a large group of people? How did it go?",
                "What is the strangest dream you have ever had?",
                "What is a controversial opinion you have?",
                " Who in your life brings you the most joy?",
                "Who had the biggest impact on the person you have become?",
                "What is the most annoying habit someone can have?",
                "Where is the most beautiful place you have been?",
                "Where do you spend most of your free time/day?",
                "Who was your best friend in elementary school?",
                "How often do you stay up past 3 a.m.?",
                " What’s your favorite season? Why?",
                "Which is more important, having a great car or a great house? Why?",
                "What animal or insect do you wish humans could eradicate?",
                "What do you bring with you everywhere you go?",
                "How much time do you spend on the internet? What do you usually do?",
                "What is the most disgusting habit some people have?",
                "Where and when was the most amazing sunset you have ever seen?",
                "Which recent news story is the most interesting?",
                "Where is the worst place you have been stuck for a long time?",
                "If you had to change your name, what would your new name be?",
                "What is something that really annoys you but doesn’t bother most people?",
                "What word or saying from the past do you think should come back?",
                "How should success be measured? And by that measurement, who is the most successful person you know?",
                "What is your guilty pleasure?",
                "Was there ever an event in your life that defied explanation?",
                "If you could learn the answer to one question about your future, what would the question be?",
                "Has anyone ever saved your life?",
                "What benefit do you bring to the group when you hang out with friends?",
                "How often do you curse? And what’s your go-to string of curse words?",
                "What trends did you follow when you were younger?",
                " What do you fear is hiding in the dark?",
                "What was the best period of your life so far? What do you think will be the best period of your entire life?",
                "What do you do to improve your mood when you are in a bad mood?",
            ]
            let Responses = responses[Math.floor(Math.random()*responses.length)-1]
            message.channel.send(`${Responses}`)
        }
    }